#### Dockerfile in project conway25JavaMqtt
FROM eclipse-temurin:17.0.5_8-jre-focal

WORKDIR /app

# Copia il JAR corretto
COPY build/libs/conway25JavaMqtt-1.0.jar /app.jar

# Comando per eseguire l'applicazione
CMD ["java", "-jar", "/app.jar"]
